fix/changelog
acs-dl/admin-panel pull request #5
Opened 2023-10-05 11:37 UTC by yehor-podporinov

2023-10-09 08:26 UTC, ArtSuslov requested changes

2023-10-09 08:26 UTC, ArtSuslov commented on CHANGELOG.md
> +## [0.4.0] - 2023-07-05
- how did you add tag to changelog and unreleased at the same time?
- you removed brackets on other tags and added brackets to this one

2023-10-09 08:26 UTC, ArtSuslov commented on package.json
> -  "version": "0.3.0",
?

2023-10-09 08:26 UTC, ArtSuslov commented on CHANGELOG.md
> +[0.3.0]: https://github.com/acs-dl/admin-panel/tree/v0.3.0
why did you remove prev tags?

2023-10-09 13:16 UTC, yehor-podporinov commented on package.json
> -  "version": "0.3.0",
done

2023-10-10 10:36 UTC, yehor-podporinov commented on CHANGELOG.md
> +[0.3.0]: https://github.com/acs-dl/admin-panel/tree/v0.3.0
discussed, done

2023-10-10 10:57 UTC, ArtSuslov approved these changes

2023-10-10 12:21 UTC, merged